// Fruits
import fruit_1 from "../../images/apple.jpg";
import fruit_2 from "../../images/apricot.webp";
import fruit_3 from "../../images/banana.png";
import fruit_4 from "../../images/blackberry.jpg";
import fruit_5 from "../../images/cherry.png";
import fruit_6 from "../../images/Grapes.webp";
import fruit_7 from "../../images/kiwi.png";
import fruit_8 from "../../images/mango.jpg";
import fruit_9 from "../../images/pineapple.webp";
import fruit_10 from "../../images/strawberry.jpg";
import fruit_11 from "../../images/watermelon.jpg";
import fruit_12 from "../../images/jackfruit.png";
import fruit_13 from "../../images/orange.jpg";
// Vegetables
import veg_1 from "../../images/avocado.png";
import veg_2 from "../../images/bellpaper.jpg";
import veg_3 from "../../images/bitter-gourd.jpg";
import veg_4 from "../../images/brinjal.jpg";
import veg_5 from "../../images/brocoli.jpg";
import veg_6 from "../../images/carrot.jpg";
import veg_7 from "../../images/cauliflower.jpg";
import veg_8 from "../../images/drumsticks.jpg";
import veg_9 from "../../images/ladyfinger.jpg";
import veg_10 from "../../images/lemon.jpg";
import veg_11 from "../../images/peas.jpg";
import veg_12 from "../../images/raddish.jpg";
import veg_13 from "../../images/tomato.jpg";
// // Dairy & Egg Products
import dairy_1 from "../../images/bread.jpg";
import dairy_2 from "../../images/butter.webp";
import dairy_3 from "../../images/cheese.webp";
import dairy_4 from "../../images/condensedmilk.webp";
import dairy_5 from "../../images/cream.png";
import dairy_6 from "../../images/curd.jpg";
import dairy_7 from "../../images/egg.jpg";
import dairy_8 from "../../images/evaporatedmilk.jpg";
import dairy_9 from "../../images/ghee.webp";
import dairy_10 from "../../images/mayonnaise.webp";
import dairy_11 from "../../images/milk.webp";
import dairy_12 from "../../images/powderedmilk.jpg";
// // Snakes & Beverges
import one from "../../images/chips.jpg";
import two from "../../images/nuts.jpg";
import three from "../../images/softdrink.png";
import four from "../../images/popcorn.jpg";
import five from "../../images/potatochips.jpg";
import six from "../../images/crackers.png";
import seven from "../../images/sparklingwater.jpg";
import eight from "../../images/ricecrackers.jpg";
import nine from "../../images/muffins.jpg";
import ten from "../../images/smoothie.jpg";
import eleven from "../../images/donuts.webp";
import twelve from "../../images/veggiesticks.jpg";
import thirteen from "../../images/coldcoffee.jpg";
import fourteen from "../../images/cookies.jpg";
import fifteen from "../../images/iceddrink.jpg";
import sixteen from "../../images/tortillachips.jpg";
import seventeen from "../../images/juice.jpg";
import eighteen from "../../images/cupcakes.jpg";
import nineteen from "../../images/driedfruits.png";
import twenty from "../../images/kombucha.jpg";
import { StaticImageData } from "next/image";

export interface ProductItem {
  id: number;
  title: string;
  image: StaticImageData;
  dPrice: number; // Discounted Price
  oPrice: number; // Original Price
  description: string;
  weight: string;
  category: string;
  rating: number;
  reviews: number;
  nutritionalInfo: {
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
  };
  origin: string;
}

export interface ProductCategory {
  fruitItems?: ProductItem[];
  vegItems?: ProductItem[];
  dairyItems?: ProductItem[];
  snackItems?: ProductItem[];
}

export const products: ProductCategory[] = [
  {
    fruitItems: [
      {
        id: 1,
        title: "Apple",
        image: fruit_1,
        dPrice: 90,
        oPrice: 99,
        description: "Fresh and crispy apples, perfect for snacking.",
        weight: "200g",
        category: "Fruit",
        rating: 4.5,
        reviews: 120,
        nutritionalInfo: {
          calories: 52,
          protein: 0.3,
          carbs: 14,
          fat: 0.2,
        },
        origin: "USA",
      },
      {
        id: 2,
        title: "Apricot",
        image: fruit_2,
        dPrice: 90,
        oPrice: 99,
        description: "Sweet, juicy apricots that are rich in vitamin A.",
        weight: "150g",
        category: "Fruit",
        rating: 4.2,
        reviews: 100,
        nutritionalInfo: {
          calories: 48,
          protein: 1,
          carbs: 12,
          fat: 0.4,
        },
        origin: "Turkey",
      },
      {
        id: 3,
        title: "Banana",
        image: fruit_3,
        dPrice: 90,
        oPrice: 99,
        description:
          "A bunch of ripe bananas, great for smoothies and desserts.",
        weight: "250g",
        category: "Fruit",
        rating: 4.8,
        reviews: 150,
        nutritionalInfo: {
          calories: 89,
          protein: 1.1,
          carbs: 23,
          fat: 0.3,
        },
        origin: "Ecuador",
      },
      {
        id: 4,
        title: "BlackBerry",
        image: fruit_4,
        dPrice: 90,
        oPrice: 99,
        description: "Fresh blackberries full of antioxidants.",
        weight: "100g",
        category: "Fruit",
        rating: 4.7,
        reviews: 80,
        nutritionalInfo: {
          calories: 43,
          protein: 1.4,
          carbs: 10,
          fat: 0.5,
        },
        origin: "USA",
      },
      {
        id: 5,
        title: "Cherry",
        image: fruit_5,
        dPrice: 90,
        oPrice: 99,
        description: "Sweet and tart cherries for a refreshing snack.",
        weight: "150g",
        category: "Fruit",
        rating: 4.6,
        reviews: 95,
        nutritionalInfo: {
          calories: 50,
          protein: 1,
          carbs: 12,
          fat: 0.3,
        },
        origin: "Turkey",
      },
      {
        id: 6,
        title: "Grapes",
        image: fruit_6,
        dPrice: 90,
        oPrice: 99,
        description:
          "Juicy red grapes, perfect for snacking or adding to salads.",
        weight: "200g",
        category: "Fruit",
        rating: 4.9,
        reviews: 110,
        nutritionalInfo: {
          calories: 69,
          protein: 0.7,
          carbs: 18,
          fat: 0.2,
        },
        origin: "Spain",
      },
      {
        id: 7,
        title: "Kiwi",
        image: fruit_7,
        dPrice: 90,
        oPrice: 99,
        description: "Tart and tangy kiwis packed with vitamin C.",
        weight: "100g",
        category: "Fruit",
        rating: 4.4,
        reviews: 75,
        nutritionalInfo: {
          calories: 61,
          protein: 1.1,
          carbs: 15,
          fat: 0.5,
        },
        origin: "New Zealand",
      },
      {
        id: 8,
        title: "Mango",
        image: fruit_8,
        dPrice: 90,
        oPrice: 99,
        description: "Sweet and succulent mangoes from tropical regions.",
        weight: "250g",
        category: "Fruit",
        rating: 5,
        reviews: 200,
        nutritionalInfo: {
          calories: 60,
          protein: 0.8,
          carbs: 15,
          fat: 0.4,
        },
        origin: "India",
      },
      {
        id: 9,
        title: "PineApple",
        image: fruit_9,
        dPrice: 90,
        oPrice: 99,
        description:
          "Tropical pineapple with a refreshing sweet and sour taste.",
        weight: "500g",
        category: "Fruit",
        rating: 4.3,
        reviews: 90,
        nutritionalInfo: {
          calories: 50,
          protein: 0.5,
          carbs: 13,
          fat: 0.1,
        },
        origin: "Philippines",
      },
      {
        id: 10,
        title: "StrawBerry",
        image: fruit_10,
        dPrice: 90,
        oPrice: 99,
        description: "Fresh strawberries that are sweet and juicy.",
        weight: "150g",
        category: "Fruit",
        rating: 4.9,
        reviews: 150,
        nutritionalInfo: {
          calories: 32,
          protein: 0.7,
          carbs: 8,
          fat: 0.3,
        },
        origin: "USA",
      },
      {
        id: 11,
        title: "WaterMelon",
        image: fruit_11,
        dPrice: 90,
        oPrice: 99,
        description:
          "Juicy watermelon slices that are perfect for hot summer days.",
        weight: "1kg",
        category: "Fruit",
        rating: 4.6,
        reviews: 120,
        nutritionalInfo: {
          calories: 30,
          protein: 0.6,
          carbs: 8,
          fat: 0.2,
        },
        origin: "Mexico",
      },
      {
        id: 12,
        title: "JackFruit",
        image: fruit_12,
        dPrice: 90,
        oPrice: 99,
        description: "Large jackfruit with a sweet and savory taste.",
        weight: "2kg",
        category: "Fruit",
        rating: 4.3,
        reviews: 65,
        nutritionalInfo: {
          calories: 95,
          protein: 1.7,
          carbs: 23,
          fat: 0.4,
        },
        origin: "India",
      },
      {
        id: 13,
        title: "Orange",
        image: fruit_13,
        dPrice: 90,
        oPrice: 99,
        description: "Fresh, tangy oranges packed with vitamin C.",
        weight: "200g",
        category: "Fruit",
        rating: 4.7,
        reviews: 135,
        nutritionalInfo: {
          calories: 47,
          protein: 0.9,
          carbs: 12,
          fat: 0.1,
        },
        origin: "Spain",
      },
    ],
    vegItems: [
      {
        id: 14,
        title: "Avocado",
        image: veg_1,
        dPrice: 90,
        oPrice: 99,
        description: "Rich, creamy avocados with healthy fats and nutrients.",
        weight: "200g",
        category: "Vegetable",
        rating: 4.8,
        reviews: 130,
        nutritionalInfo: {
          calories: 160,
          protein: 2,
          carbs: 9,
          fat: 15,
        },
        origin: "Mexico",
      },
      {
        id: 15,
        title: "BellPaper",
        image: veg_2,
        dPrice: 90,
        oPrice: 99,
        description: "Fresh bell peppers, great for salads and stir-fries.",
        weight: "150g",
        category: "Vegetable",
        rating: 4.5,
        reviews: 110,
        nutritionalInfo: {
          calories: 25,
          protein: 1,
          carbs: 6,
          fat: 0.2,
        },
        origin: "Spain",
      },
      {
        id: 16,
        title: "Bittergourd",
        image: veg_3,
        dPrice: 90,
        oPrice: 99,
        description:
          "Bitter and healthy gourd, known for its medicinal properties.",
        weight: "250g",
        category: "Vegetable",
        rating: 4.0,
        reviews: 75,
        nutritionalInfo: {
          calories: 17,
          protein: 1,
          carbs: 4,
          fat: 0.2,
        },
        origin: "India",
      },
      {
        id: 17,
        title: "Brinjal",
        image: veg_4,
        dPrice: 90,
        oPrice: 99,
        description:
          "Soft and tender brinjal, perfect for curries and roasting.",
        weight: "300g",
        category: "Vegetable",
        rating: 4.3,
        reviews: 85,
        nutritionalInfo: {
          calories: 25,
          protein: 1,
          carbs: 6,
          fat: 0.2,
        },
        origin: "India",
      },
      {
        id: 18,
        title: "Brocoli",
        image: veg_5,
        dPrice: 90,
        oPrice: 99,
        description:
          "Fresh, green broccoli that’s rich in vitamins and antioxidants.",
        weight: "250g",
        category: "Vegetable",
        rating: 4.7,
        reviews: 120,
        nutritionalInfo: {
          calories: 55,
          protein: 3.7,
          carbs: 11,
          fat: 0.6,
        },
        origin: "USA",
      },
      {
        id: 19,
        title: "Carrot",
        image: veg_6,
        dPrice: 90,
        oPrice: 99,
        description:
          "Sweet and crunchy carrots, perfect for salads or as a snack.",
        weight: "200g",
        category: "Vegetable",
        rating: 4.9,
        reviews: 150,
        nutritionalInfo: {
          calories: 41,
          protein: 0.9,
          carbs: 10,
          fat: 0.2,
        },
        origin: "India",
      },
      {
        id: 20,
        title: "CauliFlower",
        image: veg_7,
        dPrice: 90,
        oPrice: 99,
        description:
          "Fresh cauliflower, great for making low-carb rice or adding to stews.",
        weight: "400g",
        category: "Vegetable",
        rating: 4.6,
        reviews: 110,
        nutritionalInfo: {
          calories: 25,
          protein: 1.9,
          carbs: 5,
          fat: 0.3,
        },
        origin: "USA",
      },
      {
        id: 21,
        title: "Drumsticks",
        image: veg_8,
        dPrice: 90,
        oPrice: 99,
        description: "Healthy drumsticks, often used in soups and curries.",
        weight: "300g",
        category: "Vegetable",
        rating: 4.4,
        reviews: 95,
        nutritionalInfo: {
          calories: 37,
          protein: 2.1,
          carbs: 8,
          fat: 0.2,
        },
        origin: "India",
      },
      {
        id: 22,
        title: "LadyFinger",
        image: veg_9,
        dPrice: 90,
        oPrice: 99,
        description:
          "Tender and slim ladyfinger, great for frying or making curry.",
        weight: "250g",
        category: "Vegetable",
        rating: 4.8,
        reviews: 120,
        nutritionalInfo: {
          calories: 33,
          protein: 1.9,
          carbs: 7,
          fat: 0.2,
        },
        origin: "India",
      },
      {
        id: 23,
        title: "Lemon",
        image: veg_10,
        dPrice: 90,
        oPrice: 99,
        description: "Tangy and fresh lemons, packed with vitamin C.",
        weight: "100g",
        category: "Vegetable",
        rating: 4.9,
        reviews: 180,
        nutritionalInfo: {
          calories: 29,
          protein: 1.1,
          carbs: 9,
          fat: 0.3,
        },
        origin: "Spain",
      },
      {
        id: 24,
        title: "Peas",
        image: veg_11,
        dPrice: 90,
        oPrice: 99,
        description:
          "Fresh green peas, perfect for adding to dishes or eating as a snack.",
        weight: "150g",
        category: "Vegetable",
        rating: 4.7,
        reviews: 140,
        nutritionalInfo: {
          calories: 81,
          protein: 5.4,
          carbs: 14,
          fat: 0.4,
        },
        origin: "USA",
      },
      {
        id: 25,
        title: "Radddish",
        image: veg_12,
        dPrice: 90,
        oPrice: 99,
        description: "Spicy and crunchy radishes, great for adding to salads.",
        weight: "200g",
        category: "Vegetable",
        rating: 4.3,
        reviews: 90,
        nutritionalInfo: {
          calories: 16,
          protein: 0.9,
          carbs: 4,
          fat: 0.1,
        },
        origin: "India",
      },
      {
        id: 26,
        title: "Tomato",
        image: veg_13,
        dPrice: 90,
        oPrice: 99,
        description:
          "Ripe and juicy tomatoes, perfect for making sauces or adding to salads.",
        weight: "200g",
        category: "Vegetable",
        rating: 4.8,
        reviews: 160,
        nutritionalInfo: {
          calories: 18,
          protein: 0.9,
          carbs: 4,
          fat: 0.2,
        },
        origin: "Spain",
      },
    ],
    dairyItems: [
      {
        id: 27,
        title: "Bread",
        image: dairy_1,
        dPrice: 90,
        oPrice: 99,
        description: "Freshly baked bread, soft and perfect for sandwiches.",
        weight: "500g",
        category: "Dairy",
        rating: 4.7,
        reviews: 150,
        nutritionalInfo: {
          calories: 265,
          protein: 9,
          carbs: 49,
          fat: 3,
        },
        origin: "USA",
      },
      {
        id: 28,
        title: "Butter",
        image: dairy_2,
        dPrice: 90,
        oPrice: 99,
        description:
          "Creamy butter made from fresh cream, ideal for cooking and spreading.",
        weight: "250g",
        category: "Dairy",
        rating: 4.9,
        reviews: 200,
        nutritionalInfo: {
          calories: 717,
          protein: 0.9,
          carbs: 0.1,
          fat: 81,
        },
        origin: "New Zealand",
      },
      {
        id: 29,
        title: "Cheese",
        image: dairy_3,
        dPrice: 90,
        oPrice: 99,
        description: "Soft, creamy cheese with a mild taste.",
        weight: "200g",
        category: "Dairy",
        rating: 4.8,
        reviews: 180,
        nutritionalInfo: {
          calories: 402,
          protein: 25,
          carbs: 2,
          fat: 33,
        },
        origin: "France",
      },
      {
        id: 30,
        title: "Condensed Milk",
        image: dairy_4,
        dPrice: 90,
        oPrice: 99,
        description: "Sweet and creamy condensed milk, perfect for desserts.",
        weight: "400g",
        category: "Dairy",
        rating: 4.5,
        reviews: 140,
        nutritionalInfo: {
          calories: 321,
          protein: 8,
          carbs: 56,
          fat: 9,
        },
        origin: "Thailand",
      },
      {
        id: 31,
        title: "Fresh Cream",
        image: dairy_5,
        dPrice: 90,
        oPrice: 99,
        description:
          "Rich and creamy fresh cream, perfect for desserts and cooking.",
        weight: "200g",
        category: "Dairy",
        rating: 4.8,
        reviews: 170,
        nutritionalInfo: {
          calories: 339,
          protein: 2.3,
          carbs: 5,
          fat: 35,
        },
        origin: "India",
      },
      {
        id: 32,
        title: "Curd",
        image: dairy_6,
        dPrice: 90,
        oPrice: 99,
        description:
          "Fresh and creamy curd, great for making raita or as a side dish.",
        weight: "500g",
        category: "Dairy",
        rating: 4.6,
        reviews: 130,
        nutritionalInfo: {
          calories: 98,
          protein: 4.3,
          carbs: 7.5,
          fat: 4.4,
        },
        origin: "India",
      },
      {
        id: 33,
        title: "Egg",
        image: dairy_7,
        dPrice: 90,
        oPrice: 99,
        description: "Fresh eggs, perfect for baking or cooking.",
        weight: "300g",
        category: "Dairy",
        rating: 4.7,
        reviews: 160,
        nutritionalInfo: {
          calories: 68,
          protein: 5.5,
          carbs: 1.6,
          fat: 4.8,
        },
        origin: "USA",
      },
      {
        id: 34,
        title: "Evaporated Milk",
        image: dairy_8,
        dPrice: 90,
        oPrice: 99,
        description:
          "Rich and thick evaporated milk, ideal for making creamy desserts.",
        weight: "400g",
        category: "Dairy",
        rating: 4.4,
        reviews: 110,
        nutritionalInfo: {
          calories: 150,
          protein: 7,
          carbs: 12,
          fat: 8,
        },
        origin: "UK",
      },
      {
        id: 35,
        title: "Clarified Butter",
        image: dairy_9,
        dPrice: 90,
        oPrice: 99,
        description: "Pure clarified butter, great for cooking and frying.",
        weight: "250g",
        category: "Dairy",
        rating: 4.6,
        reviews: 140,
        nutritionalInfo: {
          calories: 450,
          protein: 0.3,
          carbs: 0,
          fat: 50,
        },
        origin: "India",
      },
      {
        id: 36,
        title: "Mayonnaise",
        image: dairy_10,
        dPrice: 90,
        oPrice: 99,
        description:
          "Creamy and rich mayonnaise, perfect for sandwiches and salads.",
        weight: "250g",
        category: "Dairy",
        rating: 4.7,
        reviews: 180,
        nutritionalInfo: {
          calories: 300,
          protein: 1,
          carbs: 1,
          fat: 30,
        },
        origin: "USA",
      },
      {
        id: 37,
        title: "Milk",
        image: dairy_11,
        dPrice: 90,
        oPrice: 99,
        description: "Fresh milk, great for drinking or adding to recipes.",
        weight: "1L",
        category: "Dairy",
        rating: 4.9,
        reviews: 200,
        nutritionalInfo: {
          calories: 42,
          protein: 3.4,
          carbs: 5,
          fat: 1,
        },
        origin: "India",
      },
      {
        id: 38,
        title: "Powdered Milk",
        image: dairy_12,
        dPrice: 90,
        oPrice: 99,
        description:
          "Convenient powdered milk, perfect for long-term storage and use.",
        weight: "500g",
        category: "Dairy",
        rating: 4.5,
        reviews: 140,
        nutritionalInfo: {
          calories: 496,
          protein: 27,
          carbs: 38,
          fat: 27,
        },
        origin: "Australia",
      },
    ],
    snackItems: [
      {
        id: 39,
        title: "Chips",
        image: one,
        dPrice: 90,
        oPrice: 99,
        description: "Crispy and salty chips, perfect for a quick snack.",
        weight: "150g",
        category: "Snacks",
        rating: 4.5,
        reviews: 200,
        nutritionalInfo: {
          calories: 152,
          protein: 2,
          carbs: 15,
          fat: 9,
        },
        origin: "USA",
      },
      {
        id: 40,
        title: "Nuts",
        image: two,
        dPrice: 90,
        oPrice: 99,
        description:
          "Crunchy and healthy mixed nuts, a great source of protein.",
        weight: "100g",
        category: "Snacks",
        rating: 4.8,
        reviews: 180,
        nutritionalInfo: {
          calories: 607,
          protein: 20,
          carbs: 22,
          fat: 55,
        },
        origin: "Brazil",
      },
      {
        id: 41,
        title: "Soft Drink",
        image: three,
        dPrice: 90,
        oPrice: 99,
        description: "Refreshing soft drink, perfect for hot summer days.",
        weight: "500ml",
        category: "Snacks",
        rating: 4.6,
        reviews: 210,
        nutritionalInfo: {
          calories: 150,
          protein: 0,
          carbs: 39,
          fat: 0,
        },
        origin: "USA",
      },
      {
        id: 42,
        title: "Popcorn",
        image: four,
        dPrice: 90,
        oPrice: 99,
        description: "Light and fluffy popcorn, a perfect movie-time snack.",
        weight: "200g",
        category: "Snacks",
        rating: 4.7,
        reviews: 250,
        nutritionalInfo: {
          calories: 387,
          protein: 7,
          carbs: 78,
          fat: 7,
        },
        origin: "UK",
      },
      {
        id: 43,
        title: "Potato Chips",
        image: five,
        dPrice: 90,
        oPrice: 99,
        description:
          "Classic potato chips with a crispy texture and delicious taste.",
        weight: "150g",
        category: "Snacks",
        rating: 4.5,
        reviews: 200,
        nutritionalInfo: {
          calories: 150,
          protein: 2,
          carbs: 15,
          fat: 9,
        },
        origin: "USA",
      },
      {
        id: 44,
        title: "Crackers",
        image: six,
        dPrice: 90,
        oPrice: 99,
        description:
          "Crunchy crackers that go perfectly with cheese or spreads.",
        weight: "200g",
        category: "Snacks",
        rating: 4.6,
        reviews: 220,
        nutritionalInfo: {
          calories: 130,
          protein: 3,
          carbs: 18,
          fat: 5,
        },
        origin: "Canada",
      },
      {
        id: 45,
        title: "Sparkling Water",
        image: seven,
        dPrice: 90,
        oPrice: 99,
        description:
          "Refreshing sparkling water with a hint of natural flavor.",
        weight: "500ml",
        category: "Snacks",
        rating: 4.8,
        reviews: 180,
        nutritionalInfo: {
          calories: 0,
          protein: 0,
          carbs: 0,
          fat: 0,
        },
        origin: "Italy",
      },
      {
        id: 46,
        title: "Rice Crackers",
        image: eight,
        dPrice: 90,
        oPrice: 99,
        description: "Crispy rice crackers with a light, savory flavor.",
        weight: "100g",
        category: "Snacks",
        rating: 4.4,
        reviews: 150,
        nutritionalInfo: {
          calories: 200,
          protein: 4,
          carbs: 45,
          fat: 2,
        },
        origin: "Japan",
      },
      {
        id: 47,
        title: "Muffins",
        image: nine,
        dPrice: 90,
        oPrice: 99,
        description:
          "Soft and fluffy muffins, perfect for breakfast or a snack.",
        weight: "150g",
        category: "Snacks",
        rating: 4.7,
        reviews: 230,
        nutritionalInfo: {
          calories: 340,
          protein: 6,
          carbs: 55,
          fat: 12,
        },
        origin: "UK",
      },
      {
        id: 48,
        title: "Smoothie",
        image: ten,
        dPrice: 90,
        oPrice: 99,
        description:
          "A refreshing and healthy smoothie made with fresh fruits.",
        weight: "250ml",
        category: "Snacks",
        rating: 4.8,
        reviews: 250,
        nutritionalInfo: {
          calories: 150,
          protein: 2,
          carbs: 35,
          fat: 1,
        },
        origin: "USA",
      },
      {
        id: 49,
        title: "Donuts",
        image: eleven,
        dPrice: 90,
        oPrice: 99,
        description:
          "Sweet and fluffy donuts, perfect with your morning coffee.",
        weight: "200g",
        category: "Snacks",
        rating: 4.5,
        reviews: 220,
        nutritionalInfo: {
          calories: 350,
          protein: 4,
          carbs: 50,
          fat: 18,
        },
        origin: "USA",
      },
      {
        id: 50,
        title: "Veggie Sticks",
        image: twelve,
        dPrice: 90,
        oPrice: 99,
        description:
          "Crunchy and healthy veggie sticks, a perfect snack for everyone.",
        weight: "150g",
        category: "Snacks",
        rating: 4.6,
        reviews: 200,
        nutritionalInfo: {
          calories: 150,
          protein: 3,
          carbs: 30,
          fat: 4,
        },
        origin: "India",
      },
      {
        id: 51,
        title: "Cold Coffee",
        image: thirteen,
        dPrice: 90,
        oPrice: 99,
        description:
          "Chilled cold coffee, the perfect drink for coffee lovers.",
        weight: "250ml",
        category: "Snacks",
        rating: 4.7,
        reviews: 210,
        nutritionalInfo: {
          calories: 120,
          protein: 2,
          carbs: 25,
          fat: 4,
        },
        origin: "USA",
      },
      {
        id: 52,
        title: "Cookies",
        image: fourteen,
        dPrice: 90,
        oPrice: 99,
        description:
          "Sweet and crunchy cookies, perfect for dessert or snacks.",
        weight: "200g",
        category: "Snacks",
        rating: 4.8,
        reviews: 250,
        nutritionalInfo: {
          calories: 400,
          protein: 5,
          carbs: 60,
          fat: 18,
        },
        origin: "Canada",
      },
      {
        id: 53,
        title: "Iced Drink",
        image: fifteen,
        dPrice: 90,
        oPrice: 99,
        description: "Refreshing iced drink, a perfect way to cool down.",
        weight: "500ml",
        category: "Snacks",
        rating: 4.5,
        reviews: 200,
        nutritionalInfo: {
          calories: 120,
          protein: 0,
          carbs: 30,
          fat: 0,
        },
        origin: "Australia",
      },
      {
        id: 54,
        title: "Tortilla Chips",
        image: sixteen,
        dPrice: 90,
        oPrice: 99,
        description: "Crispy tortilla chips, great for dipping or snacking.",
        weight: "150g",
        category: "Snacks",
        rating: 4.6,
        reviews: 180,
        nutritionalInfo: {
          calories: 140,
          protein: 2,
          carbs: 20,
          fat: 6,
        },
        origin: "Mexico",
      },
      {
        id: 55,
        title: "Fresh Juice",
        image: seventeen,
        dPrice: 90,
        oPrice: 99,
        description: "Freshly squeezed juice made from natural fruits.",
        weight: "250ml",
        category: "Snacks",
        rating: 4.7,
        reviews: 200,
        nutritionalInfo: {
          calories: 120,
          protein: 1,
          carbs: 28,
          fat: 0,
        },
        origin: "India",
      },
      {
        id: 56,
        title: "CupCakes",
        image: eighteen,
        dPrice: 90,
        oPrice: 99,
        description: "Delicious and fluffy cupcakes with a sweet icing.",
        weight: "150g",
        category: "Snacks",
        rating: 4.8,
        reviews: 230,
        nutritionalInfo: {
          calories: 290,
          protein: 3,
          carbs: 40,
          fat: 15,
        },
        origin: "UK",
      },
      {
        id: 57,
        title: "Dried Fruits",
        image: nineteen,
        dPrice: 90,
        oPrice: 99,
        description: "Sweet and healthy dried fruits, perfect for snacking.",
        weight: "150g",
        category: "Snacks",
        rating: 4.6,
        reviews: 210,
        nutritionalInfo: {
          calories: 250,
          protein: 3,
          carbs: 65,
          fat: 2,
        },
        origin: "USA",
      },
      {
        id: 58,
        title: "Kombucha",
        image: twenty,
        dPrice: 90,
        oPrice: 99,
        description: "A refreshing and healthy fermented tea drink.",
        weight: "250ml",
        category: "Snacks",
        rating: 4.7,
        reviews: 180,
        nutritionalInfo: {
          calories: 35,
          protein: 1,
          carbs: 8,
          fat: 0,
        },
        origin: "USA",
      },
    ],
  },
];
